// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/application/contracts/processed_file_repository.go
//
// Generated by this command:
//
//	mockgen -source src/internal/application/contracts/processed_file_repository.go -destination src/internal/application/mocks/mock_processed_file_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ddovwll/biocadtt/src/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessedFileRepository is a mock of ProcessedFileRepository interface.
type MockProcessedFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedFileRepositoryMockRecorder
	isgomock struct{}
}

// MockProcessedFileRepositoryMockRecorder is the mock recorder for MockProcessedFileRepository.
type MockProcessedFileRepositoryMockRecorder struct {
	mock *MockProcessedFileRepository
}

// NewMockProcessedFileRepository creates a new mock instance.
func NewMockProcessedFileRepository(ctrl *gomock.Controller) *MockProcessedFileRepository {
	mock := &MockProcessedFileRepository{ctrl: ctrl}
	mock.recorder = &MockProcessedFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedFileRepository) EXPECT() *MockProcessedFileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProcessedFileRepository) Create(ctx context.Context, data models.ProcessedFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProcessedFileRepositoryMockRecorder) Create(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProcessedFileRepository)(nil).Create), ctx, data)
}

// FileExists mocks base method.
func (m *MockProcessedFileRepository) FileExists(ctx context.Context, filename string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", ctx, filename)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockProcessedFileRepositoryMockRecorder) FileExists(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockProcessedFileRepository)(nil).FileExists), ctx, filename)
}
