// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/application/contracts/report_generator.go
//
// Generated by this command:
//
//	mockgen -source src/internal/application/contracts/report_generator.go -destination src/internal/application/mocks/mock_report_generator.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ddovwll/biocadtt/src/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockReportGenerator is a mock of ReportGenerator interface.
type MockReportGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockReportGeneratorMockRecorder
	isgomock struct{}
}

// MockReportGeneratorMockRecorder is the mock recorder for MockReportGenerator.
type MockReportGeneratorMockRecorder struct {
	mock *MockReportGenerator
}

// NewMockReportGenerator creates a new mock instance.
func NewMockReportGenerator(ctrl *gomock.Controller) *MockReportGenerator {
	mock := &MockReportGenerator{ctrl: ctrl}
	mock.recorder = &MockReportGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportGenerator) EXPECT() *MockReportGeneratorMockRecorder {
	return m.recorder
}

// GenerateError mocks base method.
func (m *MockReportGenerator) GenerateError(ctx context.Context, file models.ProcessedFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateError", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateError indicates an expected call of GenerateError.
func (mr *MockReportGeneratorMockRecorder) GenerateError(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateError", reflect.TypeOf((*MockReportGenerator)(nil).GenerateError), ctx, file)
}

// GenerateReport mocks base method.
func (m *MockReportGenerator) GenerateReport(ctx context.Context, unitGUID string, data []models.DeviceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateReport", ctx, unitGUID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateReport indicates an expected call of GenerateReport.
func (mr *MockReportGeneratorMockRecorder) GenerateReport(ctx, unitGUID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateReport", reflect.TypeOf((*MockReportGenerator)(nil).GenerateReport), ctx, unitGUID, data)
}
