// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/application/contracts/tsv_reader.go
//
// Generated by this command:
//
//	mockgen -source src/internal/application/contracts/tsv_reader.go -destination src/internal/application/mocks/mock_tsv_reader.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ddovwll/biocadtt/src/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTsvReader is a mock of TsvReader interface.
type MockTsvReader struct {
	ctrl     *gomock.Controller
	recorder *MockTsvReaderMockRecorder
	isgomock struct{}
}

// MockTsvReaderMockRecorder is the mock recorder for MockTsvReader.
type MockTsvReaderMockRecorder struct {
	mock *MockTsvReader
}

// NewMockTsvReader creates a new mock instance.
func NewMockTsvReader(ctrl *gomock.Controller) *MockTsvReader {
	mock := &MockTsvReader{ctrl: ctrl}
	mock.recorder = &MockTsvReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTsvReader) EXPECT() *MockTsvReaderMockRecorder {
	return m.recorder
}

// ReadDeviceData mocks base method.
func (m *MockTsvReader) ReadDeviceData(ctx context.Context, filename string) ([]models.DeviceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDeviceData", ctx, filename)
	ret0, _ := ret[0].([]models.DeviceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDeviceData indicates an expected call of ReadDeviceData.
func (mr *MockTsvReaderMockRecorder) ReadDeviceData(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDeviceData", reflect.TypeOf((*MockTsvReader)(nil).ReadDeviceData), ctx, filename)
}
