// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/application/contracts/device_data_repository.go
//
// Generated by this command:
//
//	mockgen -source src/internal/application/contracts/device_data_repository.go -destination src/internal/application/mocks/mock_device_data_repository.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ddovwll/biocadtt/src/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceDataRepository is a mock of DeviceDataRepository interface.
type MockDeviceDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceDataRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceDataRepositoryMockRecorder is the mock recorder for MockDeviceDataRepository.
type MockDeviceDataRepositoryMockRecorder struct {
	mock *MockDeviceDataRepository
}

// NewMockDeviceDataRepository creates a new mock instance.
func NewMockDeviceDataRepository(ctrl *gomock.Controller) *MockDeviceDataRepository {
	mock := &MockDeviceDataRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceDataRepository) EXPECT() *MockDeviceDataRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockDeviceDataRepository) CreateBatch(ctx context.Context, data []models.DeviceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockDeviceDataRepositoryMockRecorder) CreateBatch(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockDeviceDataRepository)(nil).CreateBatch), ctx, data)
}

// GetByUnitUUIDPaginated mocks base method.
func (m *MockDeviceDataRepository) GetByUnitUUIDPaginated(ctx context.Context, uuid string, take, offset int) (models.PaginatedData[models.DeviceData], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUnitUUIDPaginated", ctx, uuid, take, offset)
	ret0, _ := ret[0].(models.PaginatedData[models.DeviceData])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUnitUUIDPaginated indicates an expected call of GetByUnitUUIDPaginated.
func (mr *MockDeviceDataRepositoryMockRecorder) GetByUnitUUIDPaginated(ctx, uuid, take, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUnitUUIDPaginated", reflect.TypeOf((*MockDeviceDataRepository)(nil).GetByUnitUUIDPaginated), ctx, uuid, take, offset)
}
